import DS from 'ember-data';

const TEMPLATES = [
    [ "white", "white", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "white", "white", "white", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "white", "yellow", "yellow", "blue", "blue", "yellow", "yellow", "blue", "blue", "yellow", "yellow", "yellow", "yellow", "blue", "blue", "yellow", "yellow", "blue", "blue", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "black", "yellow", "yellow", "yellow", "black", "yellow", "yellow", "yellow", "yellow", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "black", "red", "red", "black", "yellow", "yellow", "yellow", "white", "yellow", "yellow", "yellow", "red", "red", "yellow", "yellow", "yellow", "white", "white", "white", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "white", "white" ],
    [ "white", "white", "black", "black", "black", "black", "black", "black", "white", "white", "white", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "black", "white", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "white", "black", "yellow", "black", "white", "black", "yellow", "black", "black", "black", "black", "yellow", "yellow", "black", "black", "yellow", "yellow", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "black", "yellow", "black", "black", "yellow", "yellow", "black", "black", "black", "black", "yellow", "yellow", "black", "white", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "black", "white", "white", "white", "black", "black", "black", "black", "black", "black", "white", "white" ],
    [ "white", "white", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "white", "white", "white", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "white", "yellow", "yellow", "black", "yellow", "yellow", "yellow", "yellow", "black", "yellow", "yellow", "yellow", "black", "yellow", "black", "yellow", "yellow", "black", "yellow", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "pink", "pink", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "pink", "pink", "pink", "pink", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "pink", "pink", "yellow", "yellow", "black", "yellow", "yellow", "yellow", "yellow", "black", "yellow", "yellow", "white", "yellow", "yellow", "black", "black", "black", "black", "yellow", "yellow", "white", "white", "white", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "white", "white" ],
    [ "white", "white", "white", "black", "black", "black", "black", "white", "white", "white", "white", "white", "black", "red", "red", "red", "red", "black", "white", "white", "white", "black", "red", "red", "red", "red", "red", "red", "black", "white", "black", "red", "red", "red", "black", "black", "red", "red", "red", "black", "black", "red", "red", "black", "white", "white", "black", "red", "red", "black", "black", "black", "black", "black", "white", "white", "black", "black", "black", "black", "black", "white", "white", "white", "black", "black", "white", "white", "white", "black", "white", "black", "white", "white", "white", "white", "white", "white", "black", "white", "white", "white", "black", "white", "white", "white", "white", "black", "white", "white", "white", "white", "white", "black", "black", "black", "black", "white", "white", "white" ],
    [ "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "teal", "teal", "teal", "teal", "teal", "teal", "teal", "teal", "teal", "teal", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "pink", "pink", "pink", "pink", "pink", "pink", "pink", "pink", "pink", "pink", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "purple", "purple", "purple", "purple", "purple", "purple", "purple", "purple", "purple", "purple", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white" ],
    [ "white", "white", "white", "red", "red", "red", "red", "white", "white", "white", "white", "white", "red", "red", "pink", "pink", "red", "red", "white", "white", "white", "white", "red", "pink", "yellow", "yellow", "pink", "red", "white", "white", "white", "white", "red", "red", "pink", "pink", "red", "red", "white", "white", "white", "white", "white", "red", "red", "red", "red", "white", "white", "white", "white", "white", "green", "white", "green", "green", "white", "white", "white", "white", "white", "white", "white", "green", "green", "green", "white", "green", "white", "white", "white", "white", "white", "white", "green", "green", "green", "white", "white", "white", "white", "white", "white", "white", "green", "green", "white", "white", "white", "white", "white", "white", "white", "white", "green", "green", "white", "white", "white", "white" ],
    [ "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "red", "red", "white", "white", "white", "white", "red", "red", "white", "red", "red", "red", "red", "white", "white", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "white", "red", "red", "red", "red", "red", "red", "red", "red", "white", "white", "white", "red", "red", "red", "red", "red", "red", "white", "white", "white", "white", "white", "red", "red", "red", "red", "white", "white", "white", "white", "white", "white", "white", "red", "red", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white" ],
    [ "white", "white", "white", "white", "white", "white", "green", "green", "white", "white", "white", "white", "white", "white", "white", "red", "red", "pink", "green", "white", "white", "white", "white", "white", "red", "red", "red", "red", "pink", "green", "white", "white", "white", "red", "red", "red", "black", "red", "pink", "green", "white", "white", "red", "red", "red", "red", "red", "red", "pink", "green", "white", "red", "red", "red", "red", "black", "red", "red", "pink", "green", "green", "red", "red", "black", "red", "red", "red", "pink", "pink", "green", "green", "green", "red", "red", "red", "red", "pink", "pink", "green", "white", "white", "green", "green", "pink", "pink", "pink", "pink", "green", "white", "white", "white", "white", "green", "green", "green", "green", "green", "white", "white", "white" ],
    [ "white", "white", "white", "white", "red", "red", "white", "white", "white", "white", "white", "white", "white", "red", "yellow", "yellow", "red", "white", "white", "white", "white", "white", "red", "yellow", "blue", "blue", "yellow", "red", "white", "white", "white", "red", "yellow", "blue", "teal", "teal", "blue", "yellow", "red", "white", "red", "yellow", "blue", "teal", "black", "black", "teal", "blue", "yellow", "red", "red", "yellow", "blue", "teal", "black", "black", "teal", "blue", "yellow", "red", "white", "red", "yellow", "blue", "teal", "teal", "blue", "yellow", "red", "white", "white", "white", "red", "yellow", "blue", "blue", "yellow", "red", "white", "white", "white", "white", "white", "red", "yellow", "yellow", "red", "white", "white", "white", "white", "white", "white", "white", "red", "red", "white", "white", "white", "white" ],
    [ "white", "white", "white", "red", "red", "red", "red", "white", "white", "white", "white", "white", "red", "yellow", "yellow", "yellow", "yellow", "red", "white", "white", "white", "red", "yellow", "green", "green", "green", "green", "yellow", "red", "white", "red", "yellow", "green", "teal", "teal", "teal", "teal", "green", "yellow", "red", "red", "yellow", "green", "teal", "black", "black", "teal", "green", "yellow", "red", "red", "yellow", "green", "teal", "black", "black", "teal", "green", "yellow", "red", "red", "yellow", "green", "teal", "teal", "teal", "teal", "green", "yellow", "red", "white", "red", "yellow", "green", "green", "green", "green", "yellow", "red", "white", "white", "white", "red", "yellow", "yellow", "yellow", "yellow", "red", "white", "white", "white", "white", "white", "red", "red", "red", "red", "white", "white", "white" ],
    [ "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "black", "white", "white", "white", "black", "white", "white", "white", "white", "white", "black", "black", "black", "black", "black", "white", "white", "white", "white", "white", "black", "black", "black", "black", "black", "white", "white", "white", "white", "white", "black", "black", "black", "black", "black", "black", "black", "black", "white", "white", "white", "black", "pink", "black", "black", "black", "black", "black", "white", "white", "white", "black", "black", "black", "black", "black", "black", "black", "white", "white", "white", "black", "white", "black", "white", "black", "white", "black", "black" ]
];

export default DS.Model.extend({
    templatePicture: DS.belongsTo('picture', {async: false}),
    playerPicture: DS.belongsTo('picture', {async: false}),

    init() {
        this._super(...arguments);

        this.set('templatePicture', this.store.createRecord('picture'));
        this.set('playerPicture', this.store.createRecord('picture'));

        this.pickRandomTemplate();
    },

    pickRandomTemplate() {
        let randomTemplate = TEMPLATES[Math.floor(Math.random() * TEMPLATES.length)];
        this.templatePicture.load(randomTemplate);
        this.playerPicture.clear();
    }
});
